# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

matrix:
  fast_finish: true
  include:
    - name: "build 64Bit"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - sudo chmod ugo+x build.sh
      script: sed -i 's/path.*=.*\".*", version/version/g' Cargo.toml && ./build.sh 64 travis

    - name: "build 32Bit"
      install:
        - sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        - cargo install cargo-xbuild
        - rustup target add armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
        - sudo chmod ugo+x build.sh
      # remove the path in the dependencies of the cargo file to ensure we use the version from crates.io
      script: sed -i 's/path.*=.*\".*", version/version/g' Cargo.toml && ./build.sh 32 travis

    - name: "unit tests"
      script: sed -i 's/path.*=.*\".*", version/version/g' Cargo.toml && cargo test --tests
